junior_car:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 1000

  Hokuyo_controller:
    type: effort_controllers/JointPositionController
    joint: hokuyo_link
    pid: {p: 100.0, i: 0.01, d: 10.0}
    
  SteerRight_controller:
    type: effort_controllers/JointPositionController
    joint: right_steer_joint
    pid: {p: 380.0, i: 50.5, d: 14.375}

  SteerLeft_controller:
    type: effort_controllers/JointPositionController
    joint: left_steer_joint
    pid: {p: 380.0, i: 50.5, d: 14.375}

  EffortDriveRight_controller:
    type: effort_controllers/JointVelocityController
    joint: right_drive_wheel_joint
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}

  EffortDriveLeft_controller:
    type: effort_controllers/JointVelocityController
    joint: left_drive_wheel_joint
    pid: {p: 1.5, i: 1.0, d: 0.0, i_clamp: 10.0}
