footprint: [[-0.556, -0.325],[-0.556, 0.325],[0.556, 0.325],[0.556, -0.325]]
footprint_padding: 0.0
transform_tolerance: 0.1
robot_base_frame: footprint
global_frame: map
update_frequency: 5.0
publish_frequency: 1.0
rolling_window: true

static:
   map_topic: map
   subscribe_to_updates: true

plugins:
   - { name: obstacles_laser, type: "costmap_2d::ObstacleLayer" }
   - { name: inflation, type: "costmap_2d::InflationLayer" }

resolution: 0.05

obstacles_laser:
   observation_sources: laser
   laser:
      {
         data_type: LaserScan,
         clearing: true,
         marking: true,
         topic: rectificated_scan,
         inf_is_valid: true,
      }

inflation_layer:
   inflation_radius: 0.7
   enabled: true

footprint_layer:
   enabled: true

sonar_layer:
   enabled: true
