TrajectoryPlannerROS:
   max_vel_x: 10
   min_vel_x: 5
   max_vel_theta: 1
   min_vel_theta: -1
   min_in_place_vel_theta: 4

   max_vel: 13
   min_vel: 7

   # velocity limits
   max_vel_lin: 12.0
   max_vel_th: 0.8
   min_vel_lin: 6.1
   min_vel_th: 0.0
   min_in_place_vel_th: 0.0
   in_place_trans_vel: 0.0
   
   acc_lim_theta: 4.0
   acc_lim_x: 2.5
   acc_lim_y: 2.5

   escape_vel: -4

   holonomic_robot: false

   sim_time: 3.0
   sim_granularity: 0.05
   vtheta_samples: 10
   dwa: true
   heading_lookahead: 1.0

   pdist_scale: 0.6
   gdist_scale: 0.4
   occdist_scale: 0.01

   xy_goal_tolerance: 0.3
   yaw_goal_tolerance: 0.2

   heading_scoring: true
   heading_scoring_times: 0.1