TebLocalPlannerROS:

 odom_topic: odom
 map_frame: /map
    
 # Trajectory
  
 teb_autosize: True
 dt_ref: 0.6
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 0
    
 # Robot

 max_vel_x: 20
 wheelbase: 0.7
 max_vel_x_backwards: 0.2
 max_vel_theta: 20
 acc_lim_x: 20
 acc_lim_theta: 20
 acc_lim_y: 20
 min_turning_radius: 1.0
 footprint_model:
   type: "polygon"
   vertices: [[-0.556, -0.325],[-0.556, 0.325],[0.556, 0.325],[0.556, -0.325]]

 # GoalTolerance
    
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.3
 free_goal_vel: False
    
 # Obstacles
    
 min_obstacle_dist: 0.6
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.5
 obstacle_poses_affected: 30
 inflation_dist: 0.6
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 7

 # Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 20
 weight_max_vel_theta: 20
 weight_acc_lim_x: 20
 weight_acc_lim_theta: 20
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 10
 weight_kinematics_turning_radius: 5
 weight_optimaltime: 1
 weight_obstacle: 10
 weight_dynamic_obstacle: 10 # not in use yet
 alternative_time_cost: False # not in use yet

 # Homotopy Class Planner

 enable_homotopy_class_planning: False
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False